Algoritmo "combinacoesPara"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Combinações
// Descrição   :
// Autor(a)    : Mayra Duarte
// Data atual  : 24/06/2023
Var
   // Seção de Declarações das variáveis
   cont1, cont2: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   para cont1 de 1 ate 3 faca
      para cont2 de 1 ate 3 faca
         escreval(cont1, cont2)
      fimpara
   fimpara
Fimalgoritmo