Algoritmo "conteAte10"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   :
// Descrição   : Contar de zero até dez
// Autor(a)    : Mayra Duarte
// Data atual  : 02/06/2023
Var
   // Seção de Declarações das variáveis
   contador: inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   contador <- 0
   enquanto (contador <= 10) faca
      escreval(contador)
      contador <- contador + 1
   fimenquanto

Fimalgoritmo