Algoritmo "OlaMundo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :
// Descrição   : Escreva um programa que mostre na tela a mensagem "Olá, mundo!"
// Autor(a)    : Mayra Duarte
// Data atual  : 15/05/2023
Var
// Seção de Declarações das variáveis
msg: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Olá, mundo!")
Escreval("Hello, world!")
msg <- "Isso é uma atribuição."
Escreva(msg)


Fimalgoritmo