Algoritmo "CassyDolar"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :
// Descrição   : Converter real por dólar usando a cotação do dia.
// Autor(a)    : Mayra Duarte
// Data atual  : 16/05/2023
Var
// Seção de Declarações das variáveis
   reais, dolar: Real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreva("Quantos reais eu tenho? R$ ")
   Leia(reais)
   dolar <- (reais / 4.94)
   Escreva("Eu posso ter US$",dolar)

Fimalgoritmo