Algoritmo "MeuNome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   :
// Descrição   : Leia o nome de uma pessoa e mostre uma mensagem de boas vindas
// Autor(a)    : Mayra Duarte
// Data atual  : 15/05/2023
Var
// Seção de Declarações das variáveis 
Nome: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite o seu nome: ")
Leia(nome)
Escreva("Muito prazer, ", nome)

Fimalgoritmo